### ISSUE TITLE
would you be able to add linear output layer?

### ISSUE THREAD

**Issue by danielazhu** [joergfranke/recnet#5]
I have a regression problem that requires a linear output layer rather than softmax output. I tried implementing my own layer following your example, in which the sequence_iteration function is as follows:

`def sequence_iteration(self, output, mask,use_dropout=0,dropout_value=0.5):

        dot_product = T.dot(output , self.t_w_out)

        net_o = T.add( dot_product , self.t_b_out )

        mask = T.addbroadcast(mask, 2) # to do nesseccary?
        output = T.mul(mask, net_o)   + T.mul( (1. - mask) , 1e-6 )

        return output #result`

But this unfortunately crashes when I try to run it.

Thanks!

**Comment by JoergFranke** [comment]
I'm really sorry but I had a large submission theses days. I just added the linear layer to the framework. Your solution was correct but you need to update the output_layer_list in super_layer.py
