### ISSUE TITLE
get_mini_batches doesn't return anything when the data set is compose of 1 sample.

### ISSUE THREAD

**Issue by chutchatut** [joergfranke/recnet#6]
Step to reproduce:
   - Generate test set of size 1
   - Call get_mini_batches
The results will be empty arrays.

**Comment by JoergFranke** [comment]
does it work with size 2? Do you really need size 1?

**Comment by chutchatut** [comment]
1) It doesn't work for size < 5. 
2) Do you have any function that could make prediction on a single file without putting them into .klepto file?
